


CREATE TABLE `mobile_food_facility_permit` (
    `id` bigint(20)  AUTO_INCREMENT not null COMMENT 'id',
	`location_id` bigint(10)  not null COMMENT 'locationid',	
	`applicant` varchar(32)  COMMENT 'applicant',
	`facility_type` int(2)  COMMENT 'facility type',
	`cnn` varchar(10)  COMMENT 'cnn',
	`location_description` varchar(200)  COMMENT 'location description',
	`address` varchar(50)  COMMENT 'address',
	`blocklot` varchar(10)  COMMENT 'block lot',
	`block` varchar(5)  COMMENT 'block',
	`lot` varchar(5)  COMMENT 'lot',
	`permit` varchar(15)  COMMENT 'permit',
	`status` int(2)  COMMENT 'status',
	`food_items` int(2)  COMMENT 'food items',	
	`X` varchar(15)  COMMENT 'X',
	`Y` varchar(15)  COMMENT 'Y',
	`latitude` varchar(20)  COMMENT 'latitude',
	`longitude` varchar(20)  COMMENT 'longitude',
	`schedule` varchar(200)  COMMENT 'schedule',
	`dayshours` varchar(50)  COMMENT 'dayshours',
	`noisent` varchar(32)  COMMENT 'noisent',
	`approved` datetime  COMMENT 'approved',
	`received` varchar(8)  COMMENT 'received',
	`prior_permit` int(1)  COMMENT 'priorpermit',
	`expiration_date` datetime  COMMENT 'expirationdate',
	`location` varchar(50)  COMMENT 'location',
	`fire_prevention_districts` int(2)  COMMENT 'fire prevention districts',
	`police_districts` int(2)  COMMENT 'police districts',
	`supervisor_districts` int(2)  COMMENT 'supervisor districts',
	`zip_codes` varchar(5)  COMMENT 'zip codes',
	`neighborhoods` int(2)  COMMENT 'neighborhoods',	
	`created_by` varchar(32) DEFAULT NULL COMMENT 'creater',
	`updated_by` varchar(32) DEFAULT NULL COMMENT 'updater',
	`created_time` datetime DEFAULT NULL COMMENT 'create time',
	`updated_time` datetime DEFAULT NULL COMMENT 'update time',
	PRIMARY KEY USING BTREE (`id`),
	UNIQUE KEY `uk_location_id` USING BTREE (`location_id`)	
) ENGINE = InnoDB DEFAULT CHARSET = utf8mb4 COMMENT 'mobile_food_facility_permit' single;
